// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '.'}],
  // docs: {
  //   'Getting Started': [
  //     'introduction',
  //     // 'how-does-it-work',
  //     // 'who-can-apply',
  //     // 'apply',
  //   ],
  //   // 'Adding DocSearch to your UI': ['dropdown', 'styling', 'behavior'],
  //   // 'Requirements, tips, FAQ': [
  //   //   'required-configuration',
  //   //   'tips',
  //   //   'faq',
  //   //   'integrations',
  //   // ],
  //   // 'Under the Hood': [
  //   //   'scraper',
  //   //   'inside-the-engine',
  //   //   'config-file',
  //   //   'how-do-we-build-an-index',
  //   //   'run-your-own',
  //   // ],
  // },
};

module.exports = sidebars;
